// <auto-generated />
using System;
using Gas_Boiler_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gas_Boiler_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129230014_ReplaceOldAlarmSystem")]
    partial class ReplaceOldAlarmSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gas_Boiler_Backend.Models.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Type", "BuildingId", "CreatedAt");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.AlarmSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertCooldownMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("CapacityAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("CapacityDeficitThreshold")
                        .HasColumnType("float");

                    b.Property<bool>("HighCostAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("HighDailyCostThreshold")
                        .HasColumnType("float");

                    b.Property<bool>("HighIndoorTempAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("HighIndoorTempThreshold")
                        .HasColumnType("float");

                    b.Property<bool>("HighOutdoorTempAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("HighOutdoorTempThreshold")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LowIndoorTempAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("LowIndoorTempThreshold")
                        .HasColumnType("float");

                    b.Property<bool>("LowOutdoorTempAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("LowOutdoorTempThreshold")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AlarmSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertCooldownMinutes = 60,
                            CapacityAlertsEnabled = true,
                            CapacityDeficitThreshold = 0.0,
                            HighCostAlertsEnabled = false,
                            HighDailyCostThreshold = 50.0,
                            HighIndoorTempAlertsEnabled = true,
                            HighIndoorTempThreshold = 28.0,
                            HighOutdoorTempAlertsEnabled = true,
                            HighOutdoorTempThreshold = 35.0,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowIndoorTempAlertsEnabled = true,
                            LowIndoorTempThreshold = 18.0,
                            LowOutdoorTempAlertsEnabled = true,
                            LowOutdoorTempThreshold = -15.0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.BuildingObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CeilingArea")
                        .HasColumnType("float");

                    b.Property<double>("CeilingUValue")
                        .HasColumnType("float");

                    b.Property<double>("DesiredTemperature")
                        .HasColumnType("float");

                    b.Property<double>("FloorArea")
                        .HasColumnType("float");

                    b.Property<double>("FloorUValue")
                        .HasColumnType("float");

                    b.Property<double>("HeatingArea")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WallArea")
                        .HasColumnType("float");

                    b.Property<double>("WallUValue")
                        .HasColumnType("float");

                    b.Property<double>("WindowArea")
                        .HasColumnType("float");

                    b.Property<double>("WindowUValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BuildingObjects");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.BuildingReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvailablePowerKw")
                        .HasColumnType("float");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyCostEur")
                        .HasColumnType("float");

                    b.Property<bool>("HasSufficientCapacity")
                        .HasColumnType("bit");

                    b.Property<double>("HeatLossWatts")
                        .HasColumnType("float");

                    b.Property<double>("IndoorTemperature")
                        .HasColumnType("float");

                    b.Property<double>("OutdoorTemperature")
                        .HasColumnType("float");

                    b.Property<double>("RequiredPowerKw")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureDifference")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingReadings");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.DataManagementSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordingIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DataManagementSettings");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.GasBoiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingObjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentPower")
                        .HasColumnType("float");

                    b.Property<double>("Efficiency")
                        .HasColumnType("float");

                    b.Property<double>("MaxPower")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("GasBoilers");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.HistoricalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("GasBoilerId")
                        .HasColumnType("int");

                    b.Property<double>("GasConsumption")
                        .HasColumnType("float");

                    b.Property<double>("InsideTemperature")
                        .HasColumnType("float");

                    b.Property<double>("OutsideTemperature")
                        .HasColumnType("float");

                    b.Property<double>("PowerOutput")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GasBoilerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoricalData");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.SystemParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CeilingUValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultBoilerEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FloorUValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GasPricePerKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GroundTemp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OutdoorDesignTemp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SafetyFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WallUValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WindowToWallRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WindowUValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SystemParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CeilingUValue = 0.25m,
                            DefaultBoilerEfficiency = 0.90m,
                            FloorUValue = 0.40m,
                            GasPricePerKwh = 0.05m,
                            GroundTemp = 10.0m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OutdoorDesignTemp = -15.0m,
                            SafetyFactor = 1.15m,
                            UpdatedBy = "System",
                            WallUValue = 0.50m,
                            WindowToWallRatio = 0.15m,
                            WindowUValue = 1.40m
                        });
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            IsBlocked = false,
                            PasswordHash = "$2a$12$xYluxINGkkohipBPd/xZLe2cJl2Y7dSomJAu5WT8MJRkd8u6J6nJW",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.Alarm", b =>
                {
                    b.HasOne("Gas_Boiler_Backend.Models.BuildingObject", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.BuildingObject", b =>
                {
                    b.HasOne("Gas_Boiler_Backend.Models.User", "User")
                        .WithMany("BuildingObjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.BuildingReading", b =>
                {
                    b.HasOne("Gas_Boiler_Backend.Models.BuildingObject", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.GasBoiler", b =>
                {
                    b.HasOne("Gas_Boiler_Backend.Models.BuildingObject", "BuildingObject")
                        .WithMany("GasBoilers")
                        .HasForeignKey("BuildingObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gas_Boiler_Backend.Models.User", "User")
                        .WithMany("GasBoilers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.HistoricalData", b =>
                {
                    b.HasOne("Gas_Boiler_Backend.Models.GasBoiler", "GasBoiler")
                        .WithMany("HistoricalData")
                        .HasForeignKey("GasBoilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GasBoiler");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.BuildingObject", b =>
                {
                    b.Navigation("GasBoilers");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.GasBoiler", b =>
                {
                    b.Navigation("HistoricalData");
                });

            modelBuilder.Entity("Gas_Boiler_Backend.Models.User", b =>
                {
                    b.Navigation("BuildingObjects");

                    b.Navigation("GasBoilers");
                });
#pragma warning restore 612, 618
        }
    }
}
